name: Nike Run Bot

on:
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *'  #  10 minutes

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install Poetry
        run: |
          curl -sSL https://install.pytcxhon-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run:  |
            python -m pip install --upgrade pip
            pip install poetry
            poetry install --no-interaction --no-ansi --no-root

      - name: Ensure storage directory exists
        run: mkdir -p src/storage

      - name: Download previous chat_ids.txt if exists
        uses: actions/download-artifact@v4
        with:
          name: datos-nikerunbot
          path: src/storage
        continue-on-error: true 

      - name: Ensure all storage files exist
        run: |
          touch src/storage/chat_ids.txt
          touch src/storage/estado_actual.txt
          touch src/storage/bot.log

      - name: Run the bot
        run: poetry run python src/check.py
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}

      - name: Upload *.txt and *.log as artifact
        uses: actions/upload-artifact@v4
        with:
            name: datos-nikerunbot
            path: |
                src/storage/estado_actual.txt
                src/storage/bot.log
                src/storage/chat_ids.txt
