name: Nike Run BA Monitor

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

permissions:
  contents: write   

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: true  
          fetch-depth: 0           
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run:  |
            python -m pip install --upgrade pip
            pip install poetry
            poetry install --no-interaction --no-ansi --no-root

      - name: Prepare storage
        run: |
          mkdir -p src/storage
          touch src/storage/chat_ids.txt
          touch src/storage/estado_actual.txt
          touch src/storage/bot.log

      - name: Run bot check
        run: poetry run python src/check.py
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          
      - name: Commit and push changes if any
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add src/storage/chat_ids.txt src/storage/estado_actual.txt
          if ! git diff --cached --exit-code; then
            git commit -m "chore: update chat_ids and estado_actual via GitHub Actions"
            git push origin HEAD:main
          else
            echo "No changes to commit"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
